In [3]:
from PIL import Image
from tensorflow.keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from tensorflow.keras.models import load_model
import numpy as np

from tensorflow.keras.preprocessing import image
model = load_model('facefeatures_new_modelx2.h5')

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        '''
        if(pred[0][0]>0.7):
            name='deepa'
        elif(pred[0][1]>0.7):
            name='bush'
        elif(pred[0][2]>0.7):
            name='numan'
        elif(pred[0][3]>0.7):
            name='sushma'
            '''
        if(pred[0][1]>0.5):
            name='numan'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()


<>:20: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:20: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Noman\AppData\Local\Temp/ipykernel_20316/882261748.py:20: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


[[1.9872374e-21 1.0000000e+00 0.0000000e+00]]
[[6.980484e-24 1.000000e+00 0.000000e+00]]
[[1.9553264e-26 1.0000000e+00 0.0000000e+00]]
[[1.774388e-23 1.000000e+00 0.000000e+00]]
[[1.1290939e-35 1.0000000e+00 0.0000000e+00]]
[[1.0132712e-37 1.0000000e+00 0.0000000e+00]]
[[0. 1. 0.]]
[[1.1350511e-24 1.0000000e+00 0.0000000e+00]]
[[7.2163954e-13 1.0000000e+00 0.0000000e+00]]
[[0.3556315  0.64436847 0.        ]]
[[8.747016e-15 1.000000e+00 0.000000e+00]]
[[1.8830036e-33 1.0000000e+00 0.0000000e+00]]
[[7.949494e-12 1.000000e+00 0.000000e+00]]
[[6.0514446e-22 1.0000000e+00 0.0000000e+00]]
[[1.747294e-13 1.000000e+00 0.000000e+00]]
[[9.8877455e-11 1.0000000e+00 0.0000000e+00]]
[[1.2980049e-06 9.9999869e-01 8.9393847e-37]]
[[1.5233662e-09 1.0000000e+00 0.0000000e+00]]
[[6.970941e-10 1.000000e+00 0.000000e+00]]
[[1.1757887e-06 9.9999881e-01 0.0000000e+00]]
[[5.497856e-13 1.000000e+00 0.000000e+00]]
[[2.4166457e-07 9.9999976e-01 0.0000000e+00]]
[[2.3933871e-06 9.9999762e-01 0.0000000e+00]]
[[7.0

In [2]:
sudo pip install tensorflow


SyntaxError: invalid syntax (<ipython-input-2-c350187f8051>, line 1)

In [4]:
pip install tensorflow


  Using cached tensorflow-2.6.0-cp38-cp38-win_amd64.whl (423.2 MB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached termcolor-1.1.0-py3-none-any.whl
  Using cached h5py-3.1.0-cp38-cp38-win_amd64.whl (2.7 MB)
  Using cached tensorflow_estimator-2.6.0-py2.py3-none-any.whl (462 kB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached tensorboard-2.6.0-py3-none-any.whl (5.6 MB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached clang-5.0-py3-none-any.whl
  Attempting uninstall: h5py
    Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install opencv-python


Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install dlib